In [1]:
import pandas as pd

### Categorical variables

In [2]:
# Let's use pandas to create Categorical Series. One way is by 
# specifying dtype="category" when constructing a Series:

s = pd.Series(["a","b","c","a"], dtype="category")
s

0    a
1    b
2    c
3    a
dtype: category
Categories (3, object): [a, b, c]

In [4]:
# Another way is to convert an existing Series or column to a 
# category dtype:

df = pd.DataFrame({"A":["a","b","c","a"]})
df["B"] = df["A"].astype('category')
df

   A  B
0  a  a
1  b  b
2  c  c
3  a  a

In [5]:
# You can also pass a pandas.Categorical object to a Series 

raw_cat = pd.Categorical(["a","b","c","a"], categories=["b","c","d"],
                          ordered=False)

In [6]:
s = pd.Series(raw_cat)
s

0    NaN
1      b
2      c
3    NaN
dtype: category
Categories (3, object): [b, c, d]

### Dummy variables

In [22]:
# Let's use pd.get_dummies to convert categorical variables into dummy 
# variables. First let's create a small DataFrame with categorical variables. 

df = pd.DataFrame({'data1': list('bbacab'), 'key': range(6)})

In [23]:
df

  data1  key
0     b    0
1     b    1
2     a    2
3     c    3
4     a    4
5     b    5

In [24]:
# Now, let's convert the categorical variables into dummy variables. 

pd.get_dummies(df['data1'])

     a    b    c
0  0.0  1.0  0.0
1  0.0  1.0  0.0
2  1.0  0.0  0.0
3  0.0  0.0  1.0
4  1.0  0.0  0.0
5  0.0  1.0  0.0

In [25]:
pd.concat([df.drop('data1',axis=1),pd.get_dummies(df['data1'])], axis = 1)

   key    a    b    c
0    0  0.0  1.0  0.0
1    1  0.0  1.0  0.0
2    2  1.0  0.0  0.0
3    3  0.0  0.0  1.0
4    4  1.0  0.0  0.0
5    5  0.0  1.0  0.0

In [54]:
 df = pd.read_csv('/Users/Rebecca/DSI-projects/curriculum/week04/3.1-dummy_variables/crunchbase_monthly_export.csv')

In [55]:
df.head()

,permalink,name,homepage_url,category_list,market,funding_total_usd,status,country_code,state_code,region,city,funding_rounds,founded_at,founded_month,founded_quarter,founded_year,first_funding_at,last_funding_at,Unnamed: 18
0,/organization/canal-do-credito,Canal do Credito,http://www.canaldocredito.com.br,|Credit|Technology|Services|Finance|,Credit,"750,000",NaN,BRA,NaN,Rio de Janeiro,Belo Horizonte,1,NaN,NaN,NaN,NaN,1/1/10,1/1/10,NaN
1,/organization/waywire,#waywire,http://www.waywire.com,|Entertainment|Politics|Social Media|News|,Entertainment,"1,750,000",acquired,USA,NY,New York City,New York,1,6/1/12,2012-06,2012-Q2,2012.0,6/30/12,6/30/12,NaN
2,/organization/tv-communications,&TV Communications,http://enjoyandtv.com,|Games|,Games,"4,000,000",operating,USA,CA,Los Angeles,Los Angeles,2,NaN,NaN,NaN,NaN,6/4/10,9/23/10,NaN
3,/organization/rock-your-paper,'Rock' Your Paper,http://www.rockyourpaper.org,|Publishing|Education|,Education,"40,000",operating,EST,NaN,Tallinn,Tallinn,1,10/26/12,2012-10,2012-Q4,2012.0,8/9/12,8/9/12,NaN
4,/organization/in-touch-network,(In)Touch Network,http://www.InTouchNetwork.com,|Electronics|Guides|Coffee|Restaurants|Music|i...,Apps,"1,500,000",operating,GBR,NaN,London,London,1,4/1/11,2011-04,2011-Q2,2011.0,4/1/11,4/1/11,NaN

In [56]:
df.columns

Index([u'permalink', u'name', u'homepage_url', u'category_list', u' market ',
       u' funding_total_usd ', u'status', u'country_code', u'state_code',
       u'region', u'city', u'funding_rounds', u'founded_at', u'founded_month',
       u'founded_quarter', u'founded_year', u'first_funding_at',
       u'last_funding_at', u'Unnamed: 18'],
      dtype='object')

In [57]:
len(df['category_list'].unique())

13192

In [58]:
len(df[' market '].unique())

548

In [59]:
pd.concat([df.drop(' market ',axis=1),pd.get_dummies(df[' market '])], axis = 1)

,permalink,name,homepage_url,category_list,funding_total_usd,status,country_code,state_code,region,city,...,Web Hosting,Web Tools,Weddings,Wholesale,Wine And Spirits,Wireless,iOS,iPad,iPhone,mHealth
0,/organization/canal-do-credito,Canal do Credito,http://www.canaldocredito.com.br,|Credit|Technology|Services|Finance|,"750,000",NaN,BRA,NaN,Rio de Janeiro,Belo Horizonte,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,/organization/waywire,#waywire,http://www.waywire.com,|Entertainment|Politics|Social Media|News|,"1,750,000",acquired,USA,NY,New York City,New York,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,/organization/tv-communications,&TV Communications,http://enjoyandtv.com,|Games|,"4,000,000",operating,USA,CA,Los Angeles,Los Angeles,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,/organization/rock-your-paper,'Rock' Your Paper,http://www.rockyourpaper.org,|Publishing|Education|,"40,000",operating,EST,NaN,Tallinn,Tallinn,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,/organization/in-touch-network,(In)Touch Network,http://www.InTouchNetwork.com,|Electronics|Guides|Coffee|Restaurants|Music|i...,"1,500,000",operating,GBR,NaN,London,London,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,/organization/n-plusn,#NAME?,http://plusn.com,|Software|,"600,000",operating,USA,NY,New York City,New York,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,/organization/club-domains,.Club Domains,http://nic.club/,|Software|,"7,000,000",NaN,USA,FL,Ft. Lauderdale,Oakland Park,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,/organization/fox-networks,.Fox Networks,http://www.dotfox.com,|Advertising|,"4,912,393",closed,ARG,NaN,Buenos Aires,Buenos Aires,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,/organization/0-6-com,0-6.com,http://www.0-6.com,|Curated Web|,"2,000,000",operating,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,/organization/004-technologies,004 Technologies,http://004gmbh.de/en/004-interact,|Software|,-,operating,USA,IL,"Springfield, Illinois",Champaign,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,/organization/0xdata,0xdata,http://www.0xdata.com,|Analytics|,"1,700,000",operating,USA,CA,SF Bay Area,Mountain View,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,/organization/1-2-3-listo,"1,2,3 Listo",http://www.123listo.com,|E-Commerce|,"40,000",operating,CHL,NaN,Santiago,Las Condes,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,/organization/1-4-all,1-4 All,NaN,|Entertainment|Games|Software|,-,operating,USA,NC,North Carolina,Connellys Springs,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,/organization/1-800-dentist,1-800-DENTIST,http://www.1800dentist.com,|Health and Wellness|,-,operating,USA,CA,Los Angeles,Los Angeles,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,/organization/1-800-doctors,1-800-DOCTORS,http://1800doctors.com,|Health and Wellness|,"1,750,000",operating,USA,NJ,Newark,Iselin,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,/organization/1-618-technology,1.618 Technology,NaN,|Real Estate|,-,operating,USA,FL,Orlando,Orlando,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,/organization/10-20-media,10-20 Media,http://www.10-20media.com,|E-Commerce|,"2,050,000",operating,USA,MD,Baltimore,Woodbine,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,/organization/1000-corks,1000 Corks,http://1000corks.com,|Search|,"40,000",operating,USA,OR,"Portland, Oregon",Lake Oswego,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18,/organization/1000-markets,1000 Markets,http://www.1000markets.com,|Marketplaces|Art|E-Commerce|,"500,000",acquired,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19,/organization/1000jobboersen-de,1000jobboersen.de,http://www.1000jobboersen.de,|Curated Web|,-,operating,DEU,NaN,Berlin,Berlin,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20,/organization/1000memories,1000memories,http://1000memories.com,|Curated Web|,"2,535,000",acquired,USA,CA,SF Bay Area,San Francisco,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
21,/organization/1000museums-com,1000museums.com,http://www.1000museums.com,|Curated Web|,"4,462,651",operating,USA,WA,Seattle,Bellevue,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
22,/organization/1001-menus,1001 Menus,http://1001menus.com,|Local Businesses|Restaurants|,"1,869,079",operating,FRA,NaN,Paris,Paris,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23,/organization/1006-tv,1006.tv,http://www.1006.tv/,|Media|Games|,"10,000,000",operating,NaN,NaN,Beijing,Beijing,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24,/organization/100du-tv,100du.tv,http://www.100du.com,|Hospitality|,"3,000,000",operating,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25,/organization/100e-com,100e.com,http://www.100e.com,|Education|,"3,000,000",operating,CHN,NaN,Beijing,Beijing,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26,/organization/100plus,100Plus,http://www.100plus.com,|Analytics|,"1,250,000",acquired,USA,CA,SF Bay Area,San Francisco,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27,/organization/1010data,1010data,http://www.1010data.com,|Software|,"35,000,000",operating,USA,NY,New York City,New York,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28,/organization/10bestthings,10BestThings,http://10bestthings.com,|Curated Web|,"50,000",closed,USA,OH,Cleveland,Cleveland,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29,/organization/10sec,10sec,https://10s.ec/,|Social Commerce|E-Commerce|Mobile Commerce|,"1,600,000",NaN,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44920,/organization/zweitgeist,zweitgeist,http://www.weblin.com,|Messaging|Software|,"651,000",operating,DEU,NaN,Hamburg,Hamburg,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
44921,/organization/zwipe,Zwipe,http://zwipe.com,|Mobile|,"3,500,000",operating,NOR,NaN,NaN,0152 Oslo,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
44922,/organization/zwittle,Zwittle,http://zwittle.com,|Software|,"190,000",operating,USA,UT,Salt Lake City,Logan,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
44923,/organization/zwoor-com,zwoor.com,http://www.zwoor.com,|Meeting Software|Polling|Surveys|Android|iPho...,"100,000",operating,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
44924,/organization/zyante,Zyante,http://www.zyante.com,|News|,"870,000",operating,USA,CA,SF Bay Area,Los Gatos,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
44925,/organization/zyb,ZYB,http://zyb.com,|Social Network Media|Networking|Mobile|,"3,845,100",acquired,DNK,NaN,Copenhagen,Copenhagen,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
44926,/organization/zyga-technology,Zyga,http://www.zyga.com,|Medical Devices|Health Care|,"45,750,000",operating,USA,MN,Minneapolis,Minnetonka,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
44927,/organization/zygo,Zygo Communications,http://www.zygocommunications.com/who,|SMS|Mobile|,-,closed,GBR,NaN,London,London,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
44928,/organization/zygo-corporation,Zygo Corporation,http://www.zygo.com,|Manufacturing|,"9,000,000",NaN,USA,CT,Connecticut,Middlefield,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
44929,/organization/zyken-nightcove,Zyken - NightCove,http://www.zyken.com,|Design|Health and Wellness|Hardware + Software|,"3,384,225",acquired,FRA,NaN,Paris,Paris-l'hopital,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
44930,/organization/zykis,Zykis,http://zykis.com,|Data Security|Automotive|Portals|Education|Ki...,"800,000",closed,USA,CA,Anaheim,Irvine,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
44931,/organization/zylie-the-bear,Zylie the Bear,http://zyliethebear.com,|E-Commerce|,"75,000",operating,USA,CT,Hartford,Greenwich,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
44932,/organization/zyme-solutions,Zyme Solutions,http://www.zymesolutions.com,|Hardware|Hardware + Software|,"12,039,999",operating,USA,CA,California,Redwood Shores,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
44933,/organization/zymetis,Zymetis,http://www.zymetis.com,|Biotechnology|,"2,257,464",closed,USA,MD,Maryland,College Park,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
44934,/organization/zymeworks,Zymeworks,http://zymeworks.com,|Biotechnology|,"38,900,000",operating,CAN,AB,Vancouver,Vancouver,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
44935,/organization/zympi,Zympi,http://www.zympi.com,|Networking|Web Hosting|Mobile|,-,operating,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
44936,/organization/zyncd,Zyncd,http://www.zyncd.com,|Knowledge Management|Crowdsourcing|,-,operating,GBR,NaN,London,London,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
44937,/organization/zyncro,Zyncro,http://www.zyncro.com,|Social Business|Enterprise 2.0|Cloud Computin...,"3,805,520",operating,ESP,NaN,Barcelona,Barcelona,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
44938,/organization/zynga,Zynga,http://www.zynga.com,|Technology|Facebook Applications|Networking|G...,"866,550,786",operating,USA,CA,SF Bay Area,San Francisco,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
44939,/organization/zyngenia,Zyngenia,http://www.zyngenia.com,|Biotechnology|,"25,000,000",operating,USA,MD,Maryland,Gaithersburg,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
44940,/organization/zynstra,Zynstra,http://www.zynstra.com,|Software|,"14,750,000",operating,GBR,NaN,Bath,Bath,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
44941,/organization/zyomyx-inc,ZYOMYX,http://www.zyomyx.com,|Biotechnology|,"34,275,015",operating,USA,MO,Missouri,Fremont,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
44942,/organization/zyraz-technology,Zyraz Technology,http://www.zyraz.com,|Biotechnology|,"15,398,910",closed,MYS,NaN,Kuala Lumpur,Damansara New Village,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
44943,/organization/zyrra,Zyrra,http://www.zyrra.com,|E-Commerce|,"1,510,500",operating,USA,MA,Boston,Cambridge,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
44944,/organization/zytoprotec,Zytoprotec,http://www.zytoprotec.com,|Biotechnology|,"2,686,600",operating,AUT,NaN,Gerasdorf Bei Wien,Gerasdorf Bei Wien,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
44945,/organization/zzish,Zzish,http://www.zzish.com,|Analytics|Gamification|Developer APIs|iOS|And...,"120,000",operating,GBR,NaN,London,London,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
44946,/organization/zznode-science-and-technology-co...,ZZNode Science and Technology,http://www.zznode.com,|Enterprise Software|,"1,587,301",operating,CHN,NaN,Beijing,Beijing,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
44947,/organization/zzzzapp-com,Zzzzapp!,http://www.zzzzapp.com,|Web Development|Advertising|Wireless|Mobile|,"71,525",operating,HRV,NaN,Split,Split,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
44948,/organization/a-list-games,[a]list games,http://www.alistgames.com,|Games|,"9,300,000",operating,NaN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
44949,/organization/x,[x+1],http://www.xplusone.com/,|Enterprise Software|,"45,000,000",operating,USA,NY,New York City,New York,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [60]:
len(df['status'].unique())

4

In [61]:
df['key'] = range(len(df))

In [62]:
pd.concat([df.drop('status',axis=1),pd.get_dummies(df['status'])], axis = 1)

,permalink,name,homepage_url,category_list,market,funding_total_usd,country_code,state_code,region,city,...,founded_month,founded_quarter,founded_year,first_funding_at,last_funding_at,Unnamed: 18,key,acquired,closed,operating
0,/organization/canal-do-credito,Canal do Credito,http://www.canaldocredito.com.br,|Credit|Technology|Services|Finance|,Credit,"750,000",BRA,NaN,Rio de Janeiro,Belo Horizonte,...,NaN,NaN,NaN,1/1/10,1/1/10,NaN,0,0.0,0.0,0.0
1,/organization/waywire,#waywire,http://www.waywire.com,|Entertainment|Politics|Social Media|News|,Entertainment,"1,750,000",USA,NY,New York City,New York,...,2012-06,2012-Q2,2012.0,6/30/12,6/30/12,NaN,1,1.0,0.0,0.0
2,/organization/tv-communications,&TV Communications,http://enjoyandtv.com,|Games|,Games,"4,000,000",USA,CA,Los Angeles,Los Angeles,...,NaN,NaN,NaN,6/4/10,9/23/10,NaN,2,0.0,0.0,1.0
3,/organization/rock-your-paper,'Rock' Your Paper,http://www.rockyourpaper.org,|Publishing|Education|,Education,"40,000",EST,NaN,Tallinn,Tallinn,...,2012-10,2012-Q4,2012.0,8/9/12,8/9/12,NaN,3,0.0,0.0,1.0
4,/organization/in-touch-network,(In)Touch Network,http://www.InTouchNetwork.com,|Electronics|Guides|Coffee|Restaurants|Music|i...,Apps,"1,500,000",GBR,NaN,London,London,...,2011-04,2011-Q2,2011.0,4/1/11,4/1/11,NaN,4,0.0,0.0,1.0
5,/organization/n-plusn,#NAME?,http://plusn.com,|Software|,Software,"600,000",USA,NY,New York City,New York,...,2012-01,2012-Q1,2012.0,8/29/12,8/29/12,NaN,5,0.0,0.0,1.0
6,/organization/club-domains,.Club Domains,http://nic.club/,|Software|,Software,"7,000,000",USA,FL,Ft. Lauderdale,Oakland Park,...,2011-10,2011-Q4,2011.0,5/31/13,5/31/13,NaN,6,0.0,0.0,0.0
7,/organization/fox-networks,.Fox Networks,http://www.dotfox.com,|Advertising|,Advertising,"4,912,393",ARG,NaN,Buenos Aires,Buenos Aires,...,NaN,NaN,NaN,1/16/07,1/16/07,NaN,7,0.0,1.0,0.0
8,/organization/0-6-com,0-6.com,http://www.0-6.com,|Curated Web|,Curated Web,"2,000,000",NaN,NaN,NaN,NaN,...,2007-01,2007-Q1,2007.0,3/19/08,3/19/08,NaN,8,0.0,0.0,1.0
9,/organization/004-technologies,004 Technologies,http://004gmbh.de/en/004-interact,|Software|,Software,-,USA,IL,"Springfield, Illinois",Champaign,...,2010-01,2010-Q1,2010.0,7/24/14,7/24/14,NaN,9,0.0,0.0,1.0
10,/organization/0xdata,0xdata,http://www.0xdata.com,|Analytics|,Analytics,"1,700,000",USA,CA,SF Bay Area,Mountain View,...,2011-01,2011-Q1,2011.0,1/3/13,1/3/13,NaN,10,0.0,0.0,1.0
11,/organization/1-2-3-listo,"1,2,3 Listo",http://www.123listo.com,|E-Commerce|,E-Commerce,"40,000",CHL,NaN,Santiago,Las Condes,...,2012-01,2012-Q1,2012.0,2/18/13,2/18/13,NaN,11,0.0,0.0,1.0
12,/organization/1-4-all,1-4 All,NaN,|Entertainment|Games|Software|,Entertainment,-,USA,NC,North Carolina,Connellys Springs,...,NaN,NaN,NaN,4/21/13,4/21/13,NaN,12,0.0,0.0,1.0
13,/organization/1-800-dentist,1-800-DENTIST,http://www.1800dentist.com,|Health and Wellness|,Health and Wellness,-,USA,CA,Los Angeles,Los Angeles,...,1986-01,1986-Q1,1986.0,8/19/10,8/19/10,NaN,13,0.0,0.0,1.0
14,/organization/1-800-doctors,1-800-DOCTORS,http://1800doctors.com,|Health and Wellness|,Health and Wellness,"1,750,000",USA,NJ,Newark,Iselin,...,1984-01,1984-Q1,1984.0,3/2/11,3/2/11,NaN,14,0.0,0.0,1.0
15,/organization/1-618-technology,1.618 Technology,NaN,|Real Estate|,Real Estate,-,USA,FL,Orlando,Orlando,...,2013-12,2013-Q4,2013.0,1/22/14,1/22/14,NaN,15,0.0,0.0,1.0
16,/organization/10-20-media,10-20 Media,http://www.10-20media.com,|E-Commerce|,E-Commerce,"2,050,000",USA,MD,Baltimore,Woodbine,...,2001-01,2001-Q1,2001.0,6/18/09,12/28/11,NaN,16,0.0,0.0,1.0
17,/organization/1000-corks,1000 Corks,http://1000corks.com,|Search|,Search,"40,000",USA,OR,"Portland, Oregon",Lake Oswego,...,2008-01,2008-Q1,2008.0,8/23/11,8/23/11,NaN,17,0.0,0.0,1.0
18,/organization/1000-markets,1000 Markets,http://www.1000markets.com,|Marketplaces|Art|E-Commerce|,Art,"500,000",NaN,NaN,NaN,NaN,...,2009-01,2009-Q1,2009.0,5/15/09,5/15/09,NaN,18,1.0,0.0,0.0
19,/organization/1000jobboersen-de,1000jobboersen.de,http://www.1000jobboersen.de,|Curated Web|,Curated Web,-,DEU,NaN,Berlin,Berlin,...,NaN,NaN,NaN,9/16/11,9/16/11,NaN,19,0.0,0.0,1.0
20,/organization/1000memories,1000memories,http://1000memories.com,|Curated Web|,Curated Web,"2,535,000",USA,CA,SF Bay Area,San Francisco,...,2010-07,2010-Q3,2010.0,1/1/10,2/16/11,NaN,20,1.0,0.0,0.0
21,/organization/1000museums-com,1000museums.com,http://www.1000museums.com,|Curated Web|,Curated Web,"4,462,651",USA,WA,Seattle,Bellevue,...,2008-01,2008-Q1,2008.0,10/14/09,1/15/14,NaN,21,0.0,0.0,1.0
22,/organization/1001-menus,1001 Menus,http://1001menus.com,|Local Businesses|Restaurants|,Local Businesses,"1,869,079",FRA,NaN,Paris,Paris,...,2010-11,2010-Q4,2010.0,12/27/12,11/13/13,NaN,22,0.0,0.0,1.0
23,/organization/1006-tv,1006.tv,http://www.1006.tv/,|Media|Games|,Games,"10,000,000",NaN,NaN,Beijing,Beijing,...,2009-01,2009-Q1,2009.0,1/1/11,7/31/14,NaN,23,0.0,0.0,1.0
24,/organization/100du-tv,100du.tv,http://www.100du.com,|Hospitality|,Hospitality,"3,000,000",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1/7/08,8/13/10,NaN,24,0.0,0.0,1.0
25,/organization/100e-com,100e.com,http://www.100e.com,|Education|,Education,"3,000,000",CHN,NaN,Beijing,Beijing,...,NaN,NaN,NaN,1/1/06,1/1/06,NaN,25,0.0,0.0,1.0
26,/organization/100plus,100Plus,http://www.100plus.com,|Analytics|,Analytics,"1,250,000",USA,CA,SF Bay Area,San Francisco,...,2011-09,2011-Q3,2011.0,11/2/11,11/30/11,NaN,26,1.0,0.0,0.0
27,/organization/1010data,1010data,http://www.1010data.com,|Software|,Software,"35,000,000",USA,NY,New York City,New York,...,2000-01,2000-Q1,2000.0,3/8/10,3/8/10,NaN,27,0.0,0.0,1.0
28,/organization/10bestthings,10BestThings,http://10bestthings.com,|Curated Web|,Curated Web,"50,000",USA,OH,Cleveland,Cleveland,...,2009-04,2009-Q2,2009.0,4/1/09,4/1/09,NaN,28,0.0,1.0,0.0
29,/organization/10sec,10sec,https://10s.ec/,|Social Commerce|E-Commerce|Mobile Commerce|,E-Commerce,"1,600,000",NaN,NaN,NaN,NaN,...,2013-07,2013-Q3,2013.0,5/8/14,5/8/14,NaN,29,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44920,/organization/zweitgeist,zweitgeist,http://www.weblin.com,|Messaging|Software|,Messaging,"651,000",DEU,NaN,Hamburg,Hamburg,...,2006-06,2006-Q2,2006.0,2/1/07,2/1/07,NaN,44920,0.0,0.0,1.0
44921,/organization/zwipe,Zwipe,http://zwipe.com,|Mobile|,Mobile,"3,500,000",NOR,NaN,NaN,0152 Oslo,...,2009-01,2009-Q1,2009.0,12/10/13,12/10/13,NaN,44921,0.0,0.0,1.0
44922,/organization/zwittle,Zwittle,http://zwittle.com,|Software|,Software,"190,000",USA,UT,Salt Lake City,Logan,...,2011-01,2011-Q1,2011.0,4/19/12,4/19/12,NaN,44922,0.0,0.0,1.0
44923,/organization/zwoor-com,zwoor.com,http://www.zwoor.com,|Meeting Software|Polling|Surveys|Android|iPho...,Android,"100,000",NaN,NaN,NaN,NaN,...,2010-01,2010-Q1,2010.0,1/1/11,1/1/11,NaN,44923,0.0,0.0,1.0
44924,/organization/zyante,Zyante,http://www.zyante.com,|News|,News,"870,000",USA,CA,SF Bay Area,Los Gatos,...,2012-01,2012-Q1,2012.0,12/1/13,4/2/14,NaN,44924,0.0,0.0,1.0
44925,/organization/zyb,ZYB,http://zyb.com,|Social Network Media|Networking|Mobile|,Mobile,"3,845,100",DNK,NaN,Copenhagen,Copenhagen,...,NaN,NaN,NaN,1/1/05,9/1/06,NaN,44925,1.0,0.0,0.0
44926,/organization/zyga-technology,Zyga,http://www.zyga.com,|Medical Devices|Health Care|,Health Care,"45,750,000",USA,MN,Minneapolis,Minnetonka,...,2008-01,2008-Q1,2008.0,10/6/08,12/16/13,NaN,44926,0.0,0.0,1.0
44927,/organization/zygo,Zygo Communications,http://www.zygocommunications.com/who,|SMS|Mobile|,Mobile,-,GBR,NaN,London,London,...,2005-06,2005-Q2,2005.0,11/19/07,11/19/07,NaN,44927,0.0,1.0,0.0
44928,/organization/zygo-corporation,Zygo Corporation,http://www.zygo.com,|Manufacturing|,Manufacturing,"9,000,000",USA,CT,Connecticut,Middlefield,...,NaN,NaN,NaN,10/24/11,10/24/11,NaN,44928,0.0,0.0,0.0
44929,/organization/zyken-nightcove,Zyken - NightCove,http://www.zyken.com,|Design|Health and Wellness|Hardware + Software|,Design,"3,384,225",FRA,NaN,Paris,Paris-l'hopital,...,2005-01,2005-Q1,2005.0,1/1/05,4/1/12,NaN,44929,1.0,0.0,0.0
44930,/organization/zykis,Zykis,http://zykis.com,|Data Security|Automotive|Portals|Education|Ki...,Automotive,"800,000",USA,CA,Anaheim,Irvine,...,2006-10,2006-Q4,2006.0,10/27/06,10/27/06,NaN,44930,0.0,1.0,0.0
44931,/organization/zylie-the-bear,Zylie the Bear,http://zyliethebear.com,|E-Commerce|,E-Commerce,"75,000",USA,CT,Hartford,Greenwich,...,2009-01,2009-Q1,2009.0,6/7/12,6/7/12,NaN,44931,0.0,0.0,1.0
44932,/organization/zyme-solutions,Zyme Solutions,http://www.zymesolutions.com,|Hardware|Hardware + Software|,Hardware,"12,039,999",USA,CA,California,Redwood Shores,...,2004-01,2004-Q1,2004.0,9/12/05,5/1/14,NaN,44932,0.0,0.0,1.0
44933,/organization/zymetis,Zymetis,http://www.zymetis.com,|Biotechnology|,Biotechnology,"2,257,464",USA,MD,Maryland,College Park,...,2006-01,2006-Q1,2006.0,1/11/10,1/31/10,NaN,44933,0.0,1.0,0.0
44934,/organization/zymeworks,Zymeworks,http://zymeworks.com,|Biotechnology|,Biotechnology,"38,900,000",CAN,AB,Vancouver,Vancouver,...,2004-04,2004-Q2,2004.0,3/3/08,1/9/14,NaN,44934,0.0,0.0,1.0
44935,/organization/zympi,Zympi,http://www.zympi.com,|Networking|Web Hosting|Mobile|,Mobile,-,NaN,NaN,NaN,NaN,...,2010-09,2010-Q3,2010.0,11/22/11,11/22/11,NaN,44935,0.0,0.0,1.0
44936,/organization/zyncd,Zyncd,http://www.zyncd.com,|Knowledge Management|Crowdsourcing|,Crowdsourcing,-,GBR,NaN,London,London,...,2014-01,2014-Q1,2014.0,2/1/14,2/1/14,NaN,44936,0.0,0.0,1.0
44937,/organization/zyncro,Zyncro,http://www.zyncro.com,|Social Business|Enterprise 2.0|Cloud Computin...,Cloud Computing,"3,805,520",ESP,NaN,Barcelona,Barcelona,...,2009-09,2009-Q3,2009.0,4/5/11,2/3/12,NaN,44937,0.0,0.0,1.0
44938,/organization/zynga,Zynga,http://www.zynga.com,|Technology|Facebook Applications|Networking|G...,Facebook Applications,"866,550,786",USA,CA,SF Bay Area,San Francisco,...,2007-07,2007-Q3,2007.0,1/1/07,2/18/11,NaN,44938,0.0,0.0,1.0
44939,/organization/zyngenia,Zyngenia,http://www.zyngenia.com,|Biotechnology|,Biotechnology,"25,000,000",USA,MD,Maryland,Gaithersburg,...,2008-01,2008-Q1,2008.0,9/9/10,9/9/10,NaN,44939,0.0,0.0,1.0
44940,/organization/zynstra,Zynstra,http://www.zynstra.com,|Software|,Software,"14,750,000",GBR,NaN,Bath,Bath,...,2011-11,2011-Q4,2011.0,3/3/12,7/9/14,NaN,44940,0.0,0.0,1.0
44941,/organization/zyomyx-inc,ZYOMYX,http://www.zyomyx.com,|Biotechnology|,Biotechnology,"34,275,015",USA,MO,Missouri,Fremont,...,1998-01,1998-Q1,1998.0,1/29/10,3/26/14,NaN,44941,0.0,0.0,1.0
44942,/organization/zyraz-technology,Zyraz Technology,http://www.zyraz.com,|Biotechnology|,Biotechnology,"15,398,910",MYS,NaN,Kuala Lumpur,Damansara New Village,...,1994-01,1994-Q1,1994.0,1/1/08,10/9/09,NaN,44942,0.0,1.0,0.0
44943,/organization/zyrra,Zyrra,http://www.zyrra.com,|E-Commerce|,E-Commerce,"1,510,500",USA,MA,Boston,Cambridge,...,NaN,NaN,NaN,10/21/10,10/18/12,NaN,44943,0.0,0.0,1.0
44944,/organization/zytoprotec,Zytoprotec,http://www.zytoprotec.com,|Biotechnology|,Biotechnology,"2,686,600",AUT,NaN,Gerasdorf Bei Wien,Gerasdorf Bei Wien,...,2007-01,2007-Q1,2007.0,1/29/13,1/29/13,NaN,44944,0.0,0.0,1.0
44945,/organization/zzish,Zzish,http://www.zzish.com,|Analytics|Gamification|Developer APIs|iOS|And...,Analytics,"120,000",GBR,NaN,London,London,...,2013-01,2013-Q1,2013.0,3/24/14,3/24/14,NaN,44945,0.0,0.0,1.0
44946,/organization/zznode-science-and-technology-co...,ZZNode Science and Technology,http://www.zznode.com,|Enterprise Software|,Enterprise Software,"1,587,301",CHN,NaN,Beijing,Beijing,...,NaN,NaN,NaN,4/1/12,4/1/12,NaN,44946,0.0,0.0,1.0
44947,/organization/zzzzapp-com,Zzzzapp!,http://www.zzzzapp.com,|Web Development|Advertising|Wireless|Mobile|,Advertising,"71,525",HRV,NaN,Split,Split,...,2012-05,2012-Q2,2012.0,11/1/11,8/1/13,NaN,44947,0.0,0.0,1.0
44948,/organization/a-list-games,[a]list games,http://www.alistgames.com,|Games|,Games,"9,300,000",NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,11/21/11,11/21/11,NaN,44948,0.0,0.0,1.0
44949,/organization/x,[x+1],http://www.xplusone.com/,|Enterprise Software|,Enterprise Software,"45,000,000",USA,NY,New York City,New York,...,1999-01,1999-Q1,1999.0,6/1/08,4/4/13,NaN,44949,0.0,0.0,1.0

In [63]:
len(df['country_code'].unique())

128

In [64]:
len(df['funding_rounds'].unique())

16

In [65]:
df.dtypes

permalink               object
name                    object
homepage_url            object
category_list           object
 market                 object
 funding_total_usd      object
status                  object
country_code            object
state_code              object
region                  object
city                    object
funding_rounds           int64
founded_at              object
founded_month           object
founded_quarter         object
founded_year           float64
first_funding_at        object
last_funding_at         object
Unnamed: 18            float64
key                      int64
dtype: object

In [66]:
df[' funding_total_usd '] = df[' funding_total_usd '].apply(lambda x: x.replace(',', ''))

In [67]:
df[' funding_total_usd '] = df[' funding_total_usd '].apply(lambda x: x.replace('-', ''))

In [77]:
df[' funding_total_usd '] = df[' funding_total_usd '].apply(lambda x: x.replace(' ', ''))

In [78]:
def fill_in(x):
    new_x = []
    for i in x:
        if i == '':
            new_x.append('NaN')
        else:
            new_x.append(float(i))
    return new_x

In [79]:
df[' funding_total_usd '][0]

'750000'

In [81]:
df[' funding_total_usd '] = fill_in(df[' funding_total_usd '])

In [82]:
df.head()

,permalink,name,homepage_url,category_list,market,funding_total_usd,status,country_code,state_code,region,city,funding_rounds,founded_at,founded_month,founded_quarter,founded_year,first_funding_at,last_funding_at,Unnamed: 18,key
0,/organization/canal-do-credito,Canal do Credito,http://www.canaldocredito.com.br,|Credit|Technology|Services|Finance|,Credit,750000,NaN,BRA,NaN,Rio de Janeiro,Belo Horizonte,1,NaN,NaN,NaN,NaN,1/1/10,1/1/10,NaN,0
1,/organization/waywire,#waywire,http://www.waywire.com,|Entertainment|Politics|Social Media|News|,Entertainment,1.75e+06,acquired,USA,NY,New York City,New York,1,6/1/12,2012-06,2012-Q2,2012.0,6/30/12,6/30/12,NaN,1
2,/organization/tv-communications,&TV Communications,http://enjoyandtv.com,|Games|,Games,4e+06,operating,USA,CA,Los Angeles,Los Angeles,2,NaN,NaN,NaN,NaN,6/4/10,9/23/10,NaN,2
3,/organization/rock-your-paper,'Rock' Your Paper,http://www.rockyourpaper.org,|Publishing|Education|,Education,40000,operating,EST,NaN,Tallinn,Tallinn,1,10/26/12,2012-10,2012-Q4,2012.0,8/9/12,8/9/12,NaN,3
4,/organization/in-touch-network,(In)Touch Network,http://www.InTouchNetwork.com,|Electronics|Guides|Coffee|Restaurants|Music|i...,Apps,1.5e+06,operating,GBR,NaN,London,London,1,4/1/11,2011-04,2011-Q2,2011.0,4/1/11,4/1/11,NaN,4